Repository 3lvia/designsystem, pull requests merged in 2024-03, with the labels that each got.

#2558 fix(web): change max width for desktop
  packages/web/src/styles.scss
Labels: design.elvia.io

#2573 fix(web): move slack feedback url from repo to env variable
  functions/slackfeedback.mts
  packages/web/angular.json
  packages/web/src/app/core/services/cms/cms.service.ts
  packages/web/src/app/shared/feedback/feedback.component.ts
Labels: design.elvia.io

#2575 refactor(web): migrate cms preview netlify function to typescript
  functions/cmspreview.mts
  functions/services.js
  package.json
  packages/web/src/app/core/services/cms/cms.service.ts
  yarn.lock
Labels: dependencies, design.elvia.io

#2564 Lego 3381 cdn stopp bygging av nye versjoner
  packages/web/src/app/core/services/version.service.ts
  packages/web/src/app/doc-pages/about/get-started-doc/get-started-doc.component.ts
  packages/web/src/app/doc-pages/components/css-library-doc/css-library-doc.component.html
  packages/web/src/app/doc-pages/components/css-library-doc/css-library-doc.component.ts
Labels: design.elvia.io

#2572 fix(web): fix breakpoint for max desktop width on web
  packages/web/src/app/shell/page-with-sidenav/page-with-sidenav.component.scss
Labels: design.elvia.io

#2588 fix(component-changelog-id.pipe): double escape of &
  packages/web/src/app/shared/component-documentation/component-changelog/component-changelog-id-pipe.ts
  packages/web/src/app/shared/component-documentation/component-changelog/component-changelog.component.ts
Labels: design.elvia.io

#2587 Lego 2680 suffiks i input css biblioteket
  packages/elvis/.internal/classlist.json
  packages/elvis/CHANGELOG.json
  packages/elvis/package.json
  packages/elvis/percy/components/input.html
  packages/elvis/src/components/form/input.scss
  packages/web/src/app/doc-pages/components/forms/input-doc/input-doc.component.html
  packages/web/src/app/doc-pages/components/forms/input-doc/input-doc.component.ts
  packages/web/src/app/doc-pages/components/forms/input-doc/input-suffix-ceg/input-suffix-ceg.component.html
  packages/web/src/app/doc-pages/components/forms/input-doc/input-suffix-ceg/input-suffix-ceg.component.scss
  packages/web/src/app/doc-pages/components/forms/input-doc/input-suffix-ceg/input-suffix-ceg.component.ts
Labels: design.elvia.io, elvis

#2589 refactor: move netlify functions to web
  netlify.toml
  package.json
  packages/web/functions/cmspreview.mts
  packages/web/functions/slackfeedback.mts
  packages/web/package.json
  yarn.lock
Labels: dependencies, design.elvia.io

#2586 Lego 3412 dropdown la overlay bli bredere enn inputfelt
  packages/components/components/elvis-dropdown/CHANGELOG.json
  packages/components/components/elvis-dropdown/package.json
  packages/components/components/elvis-dropdown/src/react/elvia-dropdown.tsx
  packages/components/components/elvis-toolbox/CHANGELOG.json
  packages/components/components/elvis-toolbox/package.json
  packages/components/components/elvis-toolbox/src/hooks/useConnectedOverlay.ts
  packages/web/src/app/dev/v2-playground/v2-playground.component.ts
  yarn.lock
Labels: dependencies, design.elvia.io, components

#2567 Lego 3408 Datepicker sender ikke value on change når value er invalid
  packages/components/components/elvis-datepicker/CHANGELOG.json
  packages/components/components/elvis-datepicker/package.json
  packages/components/components/elvis-datepicker/src/react/datepickerInput.tsx
  packages/components/components/elvis-datepicker/src/react/elvia-datepicker.tsx
  packages/react-test/src/App.tsx
  yarn.lock
Labels: dependencies, components

#2590 docs(elvis): update documentation of elvis installation
  packages/web/src/app/doc-pages/components/css-library-doc/css-library-doc.component.html
  packages/web/src/app/doc-pages/components/css-library-doc/css-library-doc.component.scss
  packages/web/src/app/doc-pages/components/css-library-doc/css-library-doc.component.ts
Labels: design.elvia.io

#2592 Lego 3416 spotlight dekker ikke hele bredden nar man forstorrer vindu
  packages/components/components/elvis-spotlight/CHANGELOG.json
  packages/components/components/elvis-spotlight/package.json
  packages/components/components/elvis-spotlight/src/react/styledComponents.tsx
Labels: components

#2595 LEGO-3417 datepicker valueOnChangeISOString gir klokkeslett
  packages/components/components/elvis-datepicker-range/CHANGELOG.json
  packages/components/components/elvis-datepicker-range/package.json
  packages/components/components/elvis-datepicker-range/src/react/elvia-datepicker-range.test.tsx
  packages/components/components/elvis-datepicker-range/src/react/elvia-datepicker-range.tsx
  packages/components/components/elvis-datepicker/CHANGELOG.json
  packages/components/components/elvis-datepicker/package.json
  packages/components/components/elvis-datepicker/src/react/elvia-datepicker.test.tsx
  packages/components/components/elvis-datepicker/src/react/elvia-datepicker.tsx
  yarn.lock
Labels: dependencies, components

#2599 chore(dateHelpers): improve type of isValidDate
  packages/components/components/elvis-datepicker-range/src/react/dateHelpers.ts
  packages/components/components/elvis-datepicker/src/react/dateHelpers.ts
Labels: components

#2600 chore(deps): yarn dedupe
  yarn.lock
Labels: dependencies

#2593 docs(dropdown): fix status icons alignment
  packages/web/src/app/doc-pages/components/dropdown-doc/dropdown-doc.component.html
Labels: design.elvia.io

#2604 feat(header): add OneTime to app drawer
  packages/components/components/elvis-header/CHANGELOG.json
  packages/components/components/elvis-header/package.json
  packages/components/components/elvis-header/src/react/elviaApps.ts
Labels: components

#2603 fix(web): dont use contentful preview API locally
  packages/web/src/app/core/services/cms/cms.service.ts
  packages/web/src/app/doc-pages/cms/cms-page/cms-page.component.ts
Labels: design.elvia.io

#2608 Lego 3422 colors dokumentasjon av nye farger
  packages/web/src/app/doc-pages/brand/color-doc/color-shade-illustration/color-shade-illustration.component.scss
  packages/web/src/app/doc-pages/brand/color-doc/color-shade-illustration/color-shade-illustration.component.svg
  packages/web/src/app/doc-pages/brand/color-doc/color-shade-illustration/color-shade-illustration.component.ts
  packages/web/src/app/doc-pages/brand/color-doc/color.component.html
  packages/web/src/app/doc-pages/brand/color-doc/color.component.scss
  packages/web/src/app/doc-pages/brand/color-doc/color.component.ts
Labels: design.elvia.io

#2605 Lego 3420 oppdater illustrasjoner til nye storrelser
  packages/elvis-illustrations/CHANGELOG.json
  packages/elvis-illustrations/README.md
  packages/elvis-illustrations/package.json
  packages/elvis-illustrations/src/illustrations/clock.svg
  packages/elvis-illustrations/src/illustrations/confirmation.svg
  packages/elvis-illustrations/src/illustrations/connected.svg
  packages/elvis-illustrations/src/illustrations/hello.svg
  packages/elvis-illustrations/src/illustrations/hidden.svg
  packages/elvis-illustrations/src/illustrations/meter-reading.svg
  packages/elvis-illustrations/src/illustrations/no-connection.svg
  packages/elvis-illustrations/src/illustrations/nothing-new.svg
  packages/elvis-illustrations/src/illustrations/office.svg
  packages/elvis-illustrations/src/illustrations/power-line.svg
  packages/elvis-illustrations/src/illustrations/price.svg
  packages/elvis-illustrations/src/illustrations/statistics.svg
  packages/elvis-illustrations/src/illustrations/support.svg
  packages/elvis-illustrations/src/illustrations/unplugged.svg
  packages/web/src/app/dev/v2-playground/v2-playground-illustrations/v2-playground-illustrations.component.html
  packages/web/src/app/dev/v2-playground/v2-playground-illustrations/v2-playground-illustrations.component.ts
Labels: design.elvia.io, tokens

#2612 chore(elvis): remove stylelint
  .stylelintrc.json
  package.json
  packages/elvis/README.md
  packages/elvis/src/components/autocomplete.scss
  packages/elvis/src/components/form/input.scss
  packages/elvis/src/components/stepper.scss
  packages/elvis/src/utilities/grid.scss
  packages/elvis/tasks/styles.js
  yarn.lock
Labels: dependencies, elvis

#2565 Lego 3153 functions seksjon header og toast
  packages/components/components/elvis-header/src/react/elviaHeader.types.tsx
  packages/web/src/app/doc-pages/components/accordion-doc/accordion-data.ts
  packages/web/src/app/doc-pages/components/autocomplete-doc/autocomplete-data.ts
  packages/web/src/app/doc-pages/components/breadcrumb-doc/breadcrumb-data.ts
  packages/web/src/app/doc-pages/components/carousel-doc/carousel-data.ts
  packages/web/src/app/doc-pages/components/chip-doc/chip-data.ts
  packages/web/src/app/doc-pages/components/component-data.interface.ts
  packages/web/src/app/doc-pages/components/context-menu-doc/context-menu-data.ts
  packages/web/src/app/doc-pages/components/dropdown-doc/dropdown-data.ts
  packages/web/src/app/doc-pages/components/forms/datepicker-doc/datepicker-data.ts
  packages/web/src/app/doc-pages/components/forms/datepicker-range-doc/datepicker-range-data.ts
  packages/web/src/app/doc-pages/components/forms/segmented-controls-doc/segmented-controls-data.ts
  packages/web/src/app/doc-pages/components/forms/timepicker-doc/timepicker-data.ts
  packages/web/src/app/doc-pages/components/header-doc/header-data.ts
  packages/web/src/app/doc-pages/components/modal-doc/modal-data.ts
  packages/web/src/app/doc-pages/components/pagination-doc/pagination-data.ts
  packages/web/src/app/doc-pages/components/popover-doc/popover-data.ts
  packages/web/src/app/doc-pages/components/radio-filter-doc/radio-filter.data.ts
  packages/web/src/app/doc-pages/components/slider-doc/slider-data.ts
  packages/web/src/app/doc-pages/components/stepper-doc/stepper-data.ts
  packages/web/src/app/doc-pages/components/tabs-doc/tabs-data.ts
  packages/web/src/app/doc-pages/components/toast-doc/toast-configuration-props.ts
  packages/web/src/app/doc-pages/components/toast-doc/toast-data.ts
  packages/web/src/app/doc-pages/components/toast-doc/toast-doc.component.html
  packages/web/src/app/doc-pages/components/toast-doc/toast-doc.component.ts
  packages/web/src/app/shared/component-documentation/component-properties-table/component-properties-table.component.ts
  packages/web/src/app/shared/component-documentation/component-properties-table/property-table-desktop/property-table-desktop.component.html
  packages/web/src/app/shared/component-documentation/component-properties-table/property-table-desktop/property-table-desktop.component.scss
  packages/web/src/app/shared/component-documentation/component-properties-table/table-base.ts
  packages/web/src/app/shared/component-documentation/component-properties-table/types.ts
Labels: design.elvia.io, components

#2614 refactor(elvis-build): migrate to esm
  package.json
  packages/elvis/.gitignore
  packages/elvis/gulpfile.mjs
  packages/elvis/package.json
  packages/elvis/tasks/classlist.mjs
  packages/elvis/tasks/icons.mjs
  packages/elvis/tasks/styles.mjs
  yarn.lock
Labels: dependencies, elvis

#2613 chore(web): remove contribute documentation
  packages/web/src/app/doc-pages/about/the-design-system-doc/the-design-system-doc.component.html
  packages/web/src/app/shared/doc-pages.ts
  packages/web/src/app/shared/shared.enum.ts
  packages/web/src/assets/doc-page-icons/shortcut-icons/Contribute.svg
  packages/web/src/assets/doc-page-icons/shortcut-icons/ContributeDark.svg
  packages/web/src/assets/doc-page-icons/shortcut-icons/ContributeOn.svg
  packages/web/src/assets/doc-page-icons/shortcut-icons/ContributeOnDark.svg
Labels: design.elvia.io

#2627 fix(modal): fix max height of mobile modal
  packages/components/components/elvis-modal/CHANGELOG.json
  packages/components/components/elvis-modal/package.json
  packages/components/components/elvis-modal/src/react/styledComponents.tsx
Labels: components

#2632 chore(web): replace favicon with svg
  packages/web/angular.json
  packages/web/src/app/app.component.ts
  packages/web/src/assets/favicon/elvia.svg
  packages/web/src/assets/favicon/favicon_final_black.zip
  packages/web/src/assets/favicon/favicon_final_black/android-chrome-192x192.png
  packages/web/src/assets/favicon/favicon_final_black/android-chrome-512x512.png
  packages/web/src/assets/favicon/favicon_final_black/apple-touch-icon.png
  packages/web/src/assets/favicon/favicon_final_black/browserconfig.xml
  packages/web/src/assets/favicon/favicon_final_black/favicon-16x16.png
  packages/web/src/assets/favicon/favicon_final_black/favicon-32x32.png
  packages/web/src/assets/favicon/favicon_final_black/favicon.ico
  packages/web/src/assets/favicon/favicon_final_black/mstile-144x144.png
  packages/web/src/assets/favicon/favicon_final_black/mstile-150x150.png
  packages/web/src/assets/favicon/favicon_final_black/mstile-310x150.png
  packages/web/src/assets/favicon/favicon_final_black/mstile-310x310.png
  packages/web/src/assets/favicon/favicon_final_black/mstile-70x70.png
  packages/web/src/assets/favicon/favicon_final_black/safari-pinned-tab.svg
  packages/web/src/assets/favicon/favicon_final_black/site.webmanifest
  packages/web/src/assets/favicon/favicon_final_white.zip
  packages/web/src/assets/favicon/favicon_final_white/android-chrome-192x192.png
  packages/web/src/assets/favicon/favicon_final_white/android-chrome-512x512.png
  packages/web/src/assets/favicon/favicon_final_white/apple-touch-icon.png
  packages/web/src/assets/favicon/favicon_final_white/browserconfig.xml
  packages/web/src/assets/favicon/favicon_final_white/favicon-16x16.png
  packages/web/src/assets/favicon/favicon_final_white/favicon-32x32.png
  packages/web/src/assets/favicon/favicon_final_white/favicon.ico
  packages/web/src/assets/favicon/favicon_final_white/mstile-144x144.png
  packages/web/src/assets/favicon/favicon_final_white/mstile-150x150.png
  packages/web/src/assets/favicon/favicon_final_white/mstile-310x150.png
  packages/web/src/assets/favicon/favicon_final_white/mstile-310x310.png
  packages/web/src/assets/favicon/favicon_final_white/mstile-70x70.png
  packages/web/src/assets/favicon/favicon_final_white/site.webmanifest
  packages/web/src/index.html
Labels: design.elvia.io

#2628 fix(input): fix disabled state in small input form fields
  packages/elvis/CHANGELOG.json
  packages/elvis/package.json
  packages/elvis/percy/components/input.html
  packages/elvis/src/components/form/input.scss
  packages/web/src/app/dev/v2-playground/v2-playground.component.html
Labels: design.elvia.io, elvis

#2633 feat(stepper): add loading state to next button in stepper
  packages/components/components/elvis-stepper/CHANGELOG.json
  packages/components/components/elvis-stepper/package.json
  packages/components/components/elvis-stepper/src/react/StepContent.tsx
  packages/components/components/elvis-stepper/src/react/publicApi.public.ts
  packages/components/components/elvis-toolbox/CHANGELOG.json
  packages/components/components/elvis-toolbox/package.json
  packages/components/components/elvis-toolbox/src/components/button/button.tsx
  packages/web/src/app/dev/v2-playground/v2-playground.component.html
  packages/web/src/app/doc-pages/components/stepper-doc/stepper-data.ts
  yarn.lock
Labels: dependencies, design.elvia.io, components

#2634 refactor(web): migrate to standalone router for app router
  packages/web/src/app/app-routing.ts
  packages/web/src/app/app.component.ts
  packages/web/src/app/doc-pages/cms/cms-page/cms-page.component.html
  packages/web/src/main.ts
Labels: design.elvia.io

#2639 fix(web): fix issues with segmented control in installation guide
  packages/web/src/app/shared/component-documentation/ceg/code-generator/code-generator.component.html
  packages/web/src/app/shared/component-documentation/ceg/code-generator/code-generator.component.ts
  packages/web/src/app/shared/component-documentation/component-installation/component-installation.component.ts
  packages/web/src/app/shared/component-documentation/preferredLanguage.service.ts
Labels: design.elvia.io

#2647 fix(web-user-questionnaire): only open modal on design.elvia.io
  packages/web/src/app/shared/user-questionnaire/user-questionnaire.component.ts
Labels: design.elvia.io

#2649 chore(deps): update @testing-library/react
  packages/components/package.json
  yarn.lock
Labels: dependencies

#2621 Lego 3413 design.elvia.io - illustrations docs
  packages/elvis-illustrations/package.json
  packages/web/src/app/app.component.ts
  packages/web/src/app/dev/v2-playground/v2-playground-illustrations/v2-playground-illustrations.component.html
  packages/web/src/app/dev/v2-playground/v2-playground-illustrations/v2-playground-illustrations.component.ts
  packages/web/src/app/dev/v2-playground/v2-playground.component.html
  packages/web/src/app/dev/v2-playground/v2-playground.component.ts
  packages/web/src/app/doc-pages/brand/brand-routing.ts
  packages/web/src/app/doc-pages/brand/illustrations-doc/illustrations-data.ts
  packages/web/src/app/doc-pages/brand/illustrations-doc/illustrations-doc.component.html
  packages/web/src/app/doc-pages/brand/illustrations-doc/illustrations-doc.component.ts
  packages/web/src/app/doc-pages/brand/illustrations-doc/illustrations-exhibit/illustrations-exhibit-data.ts
  packages/web/src/app/doc-pages/brand/illustrations-doc/illustrations-exhibit/illustrations-exhibit-details/illustrations-exhibit-details.component.html
  packages/web/src/app/doc-pages/brand/illustrations-doc/illustrations-exhibit/illustrations-exhibit-details/illustrations-exhibit-details.component.scss
  packages/web/src/app/doc-pages/brand/illustrations-doc/illustrations-exhibit/illustrations-exhibit-details/illustrations-exhibit-details.component.ts
  packages/web/src/app/doc-pages/brand/illustrations-doc/illustrations-exhibit/illustrations-exhibit-details/imageDownloadUtils.ts
  packages/web/src/app/doc-pages/brand/illustrations-doc/illustrations-exhibit/illustrations-exhibit-filter/illustrations-exhibit-filter.component.html
  packages/web/src/app/doc-pages/brand/illustrations-doc/illustrations-exhibit/illustrations-exhibit-filter/illustrations-exhibit-filter.component.scss
  packages/web/src/app/doc-pages/brand/illustrations-doc/illustrations-exhibit/illustrations-exhibit-filter/illustrations-exhibit-filter.component.ts
  packages/web/src/app/doc-pages/brand/illustrations-doc/illustrations-exhibit/illustrations-exhibit-list/illustrations-exhibit-list-display-name.pipe.ts
  packages/web/src/app/doc-pages/brand/illustrations-doc/illustrations-exhibit/illustrations-exhibit-list/illustrations-exhibit-list.component.html
  packages/web/src/app/doc-pages/brand/illustrations-doc/illustrations-exhibit/illustrations-exhibit-list/illustrations-exhibit-list.component.scss
  packages/web/src/app/doc-pages/brand/illustrations-doc/illustrations-exhibit/illustrations-exhibit-list/illustrations-exhibit-list.component.ts
  packages/web/src/app/doc-pages/brand/illustrations-doc/illustrations-exhibit/illustrations-exhibit.component.html
  packages/web/src/app/doc-pages/brand/illustrations-doc/illustrations-exhibit/illustrations-exhibit.component.scss
  packages/web/src/app/doc-pages/brand/illustrations-doc/illustrations-exhibit/illustrations-exhibit.component.ts
  packages/web/src/app/doc-pages/brand/illustrations-doc/illustrations-exhibit/illustrations-exhibit.service.ts
  packages/web/src/app/doc-pages/brand/illustrations-doc/illustrations-exhibit/illustrations-generator/illustrations-generator.component.ts
  packages/web/src/app/doc-pages/brand/illustrations-doc/illustrations-installation/illustrations-installation.component.html
  packages/web/src/app/doc-pages/brand/illustrations-doc/illustrations-installation/illustrations-installation.component.ts
  packages/web/src/app/doc-pages/components/components-routing.ts
  packages/web/src/app/home/front-page-changelog/changelogs.ts
  packages/web/src/app/home/front-page-changelog/front-page-changelog.component.html
  packages/web/src/app/shared/component-documentation/component-changelog/component-changelog.component.html
  packages/web/src/app/shared/component-documentation/component-changelog/component-changelog.component.ts
  packages/web/src/app/shared/doc-pages.ts
Labels: design.elvia.io, tokens

#2648 fix(header.component): add static header links instead of content loader
  packages/web/src/app/shell/header/header.component.html
  packages/web/src/app/shell/header/header.component.ts
Labels: design.elvia.io

#2661 fix(deps): add missing peer dependencies
  packages/components/package.json
  yarn.lock
Labels: dependencies

#2662 feat(ci): add github action to create yarn dedupe PR
  .github/workflows/yarnDedupe.yml
Labels: ci/cd

#2663 chore(ci): update github action to create yarn dedupe PR
  .github/workflows/yarnDedupe.yml
Labels: ci/cd
