Repository 3lvia/designsystem, pull requests merged in 2025-04, with the labels that each got.

#3586 deps: update to vite 6
  packages/react-test/package.json
  packages/vue-test/package.json
  packages/vue-test/src/views/Components.vue
  yarn.lock
Labels: dependencies

#3591 Update yarn.lock
  yarn.lock
Labels: dependencies

#3592 20250403 yarn
  package.json
  packages/components/components/elvis-toolbox/package.json
  packages/components/package.json
  packages/elvis-assets-icons/package.json
  packages/elvis-colors/package.json
  packages/elvis-icons/package.json
  packages/elvis-typography/package.json
  packages/react-test/package.json
  packages/vue-test/package.json
  packages/web/package.json
  yarn.lock
Labels: dependencies, design.elvia.io, components, tokens

#3593 LEGO-3699 tooltip inline styles pa tooltip virker ikke
  packages/components/components/elvis-tooltip/CHANGELOG.json
  packages/components/components/elvis-tooltip/package.json
  packages/components/components/elvis-tooltip/src/react/elvia-tooltip.tsx
  yarn.lock
Labels: dependencies, components

#3597 Update home.component.html
  .github/workflows/azure-static-web-apps-nice-sea-07f2e0703.yml
Labels: ci/cd

#3603 remove install step
  .github/workflows/azure-static-web-apps-nice-sea-07f2e0703.yml
Labels: ci/cd

#3604 Update azure-static-web-apps-nice-sea-07f2e0703.yml
  .github/workflows/azure-static-web-apps-nice-sea-07f2e0703.yml
Labels: ci/cd

#3607 Update azure-static-web-apps-nice-sea-07f2e0703.yml
  .github/workflows/azure-static-web-apps-nice-sea-07f2e0703.yml
Labels: ci/cd

#3609 Delete azure-static-web-apps-nice-sea-07f2e0703.yml
  .github/workflows/azure-static-web-apps-nice-sea-07f2e0703.yml
Labels: ci/cd

#3610 Update azure-static-web-apps-lemon-dune-011329d03.yml
  .github/workflows/azure-static-web-apps-lemon-dune-011329d03.yml
Labels: ci/cd

#3611 Oppdatere workflow
  .github/workflows/azure-static-web-apps-lemon-dune-011329d03.yml
Labels: ci/cd

#3613 legge til repo_token: ${{ secrets.GITHUB_TOKEN }}
  .github/workflows/azure-static-web-apps-lemon-dune-011329d03.yml
Labels: ci/cd

#3619 comment github_id_token
  .github/workflows/azure-static-web-apps-lemon-dune-011329d03.yml
Labels: ci/cd

#3620 Delete azure-static-web-apps-lemon-dune-011329d03.yml
  .github/workflows/azure-static-web-apps-lemon-dune-011329d03.yml
Labels: ci/cd

#3621 Update azure-static-web-apps-lively-flower-00801cb03.yml
  .github/workflows/azure-static-web-apps-lively-flower-00801cb03.yml
Labels: ci/cd

#3622 Static web app github action
  .github/workflows/azure-static-web-app-deploy.yml
Labels: ci/cd

#3625 Update docs to reflect Azure
  .gitignore
  README.md
  packages/components/README.md
  packages/elvis/README.md
  packages/web/README.md
  packages/web/package.json
  packages/web/src/app/shell/header/header.component.ts
  packages/web/src/app/shell/header/mobile-menu/mobile-menu.component.ts
  yarn.lock
Labels: dependencies, design.elvia.io, elvis

#3628 Create staticwebapp.config.json
  packages/web/staticwebapp.config.json
Labels: design.elvia.io
